### ISSUE TITLE
Very nice example.    More docs?

### ISSUE THREAD

**Issue by frankbarbarino** [Loki-Afro/multi-tenant-spring-mongodb#1]
Example works, but in a non-example solution, how would a @RestController access the MultiTenantMongoDbFactory?    @Inject into the service?    (sorry if this is more of a generic spring noob question)

**Comment by Loki-Afro** [comment]
I am using spring-boot here. 
It detects spring-mongodb from the classpath. 
A bean named `mongoDbFactory` would be present, I overrode that bean as well as `mongoTemplate`.
This is pretty much self explaining: https://github.com/spring-projects/spring-boot/blob/4d27458fee628b3846601ba03e84dbe793bbfc0e/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/mongo/MongoDataAutoConfiguration.java
