### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yuanChina** [Loki-Afro/multi-tenant-spring-mongodb#3]
Parameter 0 of method mongoTemplate in ****  required a bean of type 'com.mongodb.Mongo' that could not be found.
	- Bean method 'mongo' not loaded because @ConditionalOnMissingBean (types: org.springframework.data.mongodb.MongoDbFactory; SearchStrategy: all) found bean 'mongoDbFactory'

**Comment by Loki-Afro** [comment]
Looks like you did something wrong in your code. But how could I help you?

**Comment by yuanChina** [comment]
it has errors,  I have modified it，but other error occurred.

non-compatible bean instance of type [org.springframework.data.mongodb.core.SimpleMongoDbFactory]. Overriding bean of same name declared in: class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDataAutoConfiguration.class]

it could used with spring boot ?

**Comment by yuanChina** [comment]
it clashed with MongoAutoConfiguration in spring-boot-autoconfigure ？
